### GET request to example server
GET http://127.0.0.1:8000/history

> {%
    for (let bodyKey in response.body) {
        console.log(`${bodyKey} = ${JSON.stringify(response.body[bodyKey].status)}`)
    }
%}

### GET history by promptID
GET http://127.0.0.1:8000/history/7d4c2c23-23a0-4deb-b53a-45e0393f501e

### GET Prompt
GET http://127.0.0.1:8000/prompt
Content-Type: application/json

#> {%
#    console.log(`status ${response.status}`)
#    console.log(`queue_remaining ${response.body.exec_info.queue_remaining}`)
#%}
//{
//  "exec_info": {
//    "queue_remaining": 3
//  }
//}

### POST Prompt
POST http://127.0.0.1:8000/prompt
Content-Type: application/json

#/queue	get	retrieve the state of the queue
### GET queue
GET http://127.0.0.1:8000/queue
Content-Type: application/json

#/object_info	get	retrieve details of all node types
###  GET object_info
GET http://127.0.0.1:8000/object_info
Content-Type: application/json

#/system_stats	get	retrieve information about the system (python version, devices, vram etc)
### GET system_stats
GET http://127.0.0.1:8000/system_stats
Content-Type: application/json